on:
  push:
    branches: [main]

jobs:
  check-and-publish:
    name: Check and Publish
    runs-on: ubuntu-latest
    environment: prod
    env:
      GH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
      - name: build
        run: yarn build
      - name: publish
        run: yarn semantic-release
